// <auto-generated />
using System;
using KiotBean.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KiotBean.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KiotBean.Database.Entities.CashFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CashFlows");
                });

            modelBuilder.Entity("KiotBean.Database.Entities.CoffeePurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BagTareWeight")
                        .HasColumnType("numeric");

                    b.Property<int?>("CashFlowId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ImpurityRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Moisture")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalBags")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CashFlowId")
                        .IsUnique();

                    b.ToTable("CoffeePurchaseOrders");
                });

            modelBuilder.Entity("KiotBean.Database.Entities.CoffeePurchaseOrder", b =>
                {
                    b.HasOne("KiotBean.Database.Entities.CashFlow", "CashFlow")
                        .WithOne("PurchaseOrder")
                        .HasForeignKey("KiotBean.Database.Entities.CoffeePurchaseOrder", "CashFlowId");

                    b.Navigation("CashFlow");
                });

            modelBuilder.Entity("KiotBean.Database.Entities.CashFlow", b =>
                {
                    b.Navigation("PurchaseOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
